apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: demo
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: docker-registry-creds
      containers:
        - name: api
          image: measureapp/demo-node-api:0.0.1
          ports:
            - containerPort: 4400
          env:
            - name: API_PORT
              value: "4400"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: demo
  labels:
    app: demo-app
    job: node-api
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4400
